name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          yarn install
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: publish
          secrets: |
            API_TOKEN
            STRIPE_TOKEN
        env:
          API_TOKEN: "test-api-token"
          STRIPE_TOKEN: "test-stripe-token"
